# Exported from Render on 2025-07-05T04:40:45Z
services:
- type: web
  name: birthday-post-reminder-bot
  runtime: python
  repo: https://github.com/gfxluffy/birthday-post-reminder-bot
  plan: free
  envVars:
  - key: GOOGLE_SERVICE_ACCOUNT_JSON
    sync: false
  - key: DISCORD_CHANNEL_ID
    sync: false
  - key: DISCORD_SERVER_ID
    sync: false
  - key: DISCORD_TOKEN
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  autoDeployTrigger: commit
version: "1"
